---
title: "One Click Away"
subtitle : "Children’s experience of Internet use in Albania"
output: 
  html_document:
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
    css: my.css   # you can add your custom css, should be in same folder
---

## Access to Internet

  - Albanian children start using the Internet at an average age of 9.3 years, while the younger generation of girls and boys are more likely to start using it earlier, at 8 years or less.

  - Almost 8 in 10 children can access the Internet whenever they want or need to.

  - Parental restriction is the most common reason for children not to access the Internet always when they want or need to, especially among the youngest children (9–11 years). The high cost of Internet connection or mobile data is the second most common barrier to Internet access, and is most common among children of age 15–17 years.

  - Home is the most common place where 95.8% of children access the Internet at least weekly. Internet is also often used where the child is alone somewhere.

  - Children of age 15–17 years are online more often and in a wider range of places than younger children.

  - Smartphones are the most commonly used devices for Internet access, while more than half of children have never used a desktop computer or a tablet for Internet access.

  - Children spend an average of 2.9 hours online on a weekday,  and 3.3 hours online at a weekend.

  - Three out of ten parents of surveyed children do not use the Internet, while almost all of their children are Internet users.

## Online activities and digital skills

  - The most popular activities that children engage in online are related to entertainment, learning and social interactions.

  - The least popular activities involve community and civic
participation.

  - Children’s most developed digital skills are in the field of operational skills and social relations, while creative skills are the least developed.

  - As they get older, children engage in a wider range of activities and are more confident in their digital skills. Younger children feel less confident in skills related to their social behaviours online.

  - There is a consistent gender gap in terms of online activities and digital skills, with boys generally engaging more in online activities and having better digital skills than girls.

  - YouTube and Instagram are the most popular websites or applications among children, followed by Facebook and WhatsApp.

## Online risks and (potential) harm

  - Some 14% of children interviewed have had upsetting experiences over the Internet.

  - When something upsetting happens to them on the Internet, children tend to prefer their peers as a source of support, and are very reluctant to speak to teachers or child-care professionals.

 - The most common content risks that Albanian children face is their exposure to real violence, affecting more than 3 out 10 children.

 - Children are exposed to sexual content online mostly involuntarily, through pop-ups. At the same time, more than half of children reported seeing sexual content on the Internet because they wanted to. Only a small proportion, mostly the youngest, were upset after seeing sexual content, while the majority were either indifferent or happy about it.

  - One in four children reported had at least one contact online with someone whom they had never met face-to-face before and almost 2 in 10 reported meeting in person someone they had previously known only on the web. Only a small portion of these children were upset by these face-to-face meetings.

  - Online bullying was reported by fewer than 1 in 10 children, but this figure is probably an underestimate given the much higher levels of bullying in person.

  - One in ten children reported at least one unwanted sexual experience through the Internet. A considerable proportion of those who initiated such an experience were someone the child already knew.

  - The present study found that exposure to all forms of online risks increases with age. Also, for the most part, boys are more likely to be exposed to online risks than girls, though girls report being more upset by such experiences.

  - Parental reporting of their children’s exposure to online risks is considerably less common than the reporting by the children themselves, indicating a possible lack of communication and trust between parents and their children.

## Mediation by parents, peers and teachers

  - Children report that most of the parents surveyed do not employ an active parenting approach to their Internet use, while parents have a more positive view of their supportive engagement.

  - Parents tend to report a higher level of restrictive mediation, including through the use of parental controls and Internet monitoring, than do children.

  - There is a gender gap in terms of parental mediation, with girls being subject to more restrictive parenting than boys, including monitoring by their parents.

  - As children grow, parental mediation of Internet use becomes less restrictive.

  - Overall, the use of parental control mechanisms, such as web filtering software, seems to be at a low level.

  - Parents prefer to receive information on child online safety through schools and mass media.